### ISSUE TITLE
Best practise: error indication

### ISSUE THREAD

**Issue by weinrank** [google/fuzzing#19]
Hi all,

we're fuzzing our [usrsctp](https://github.com/sctplab/usrsctp) library and we don't clearly know how to react on internal errors.
We're executing a bunch of command before injecting the fuzzing data on each iteration.
E.g. creating a `socket()`, `bind()`, `setsockopt()`... 
We're expecting each command to be executed successfully.

In rare cases, one of these commands fails.
Question: How should we react?

Currently, we're writing an error message and call `exit()` with a non-zero return code.
The documentation says, we shouldn't call `exit()` on any input. 

If we ignore these cases, we might miss some fundamental errors in the future.
Is there a best practise to handle these cases?

@tuexen for cc notifications.

**Comment by Dor1s** [comment]
The rule of thumb is: a fuzz target should crash when it hits a bug that should be fixed. So, if you consider such errors to be valid bugs, then it's better to crash right away using an assert or calling abort() directly.

If you think those situations are OK to have, then the fuzz target should return 0; and the fuzzing will continue.

Calling exit() is the worst, as it silently ends the fuzzer execution.

From your description, it sounds to me that the right way to proceed here is to assert that every command executes successfully and then investigate and fix all the failures you'll observe.

**Comment by Dor1s** [comment]
Please re-open if needed.
