### ISSUE TITLE
[QUESTION] How can I indicate a function not to be instrumented by libfuzzer?

### ISSUE THREAD

**Issue by illera88** [google/fuzzing#89]
Is using `__attribute__((no_sanitize_address))` before the function enough? 

Or should I use the method described in the [SanitizerCoverage](https://clang.llvm.org/docs/SanitizerCoverage.html#partially-disabling-instrumentation) documentation and use a file to blacklist specific functions? 

Thank you

**Comment by morehouse** [comment]
`no_sanitize_address` will not help, since we need to disable the SanCov instrumentation instead.  The blacklist method is your best bet.
