### ISSUE TITLE
[question] Continue after crash

### ISSUE THREAD

**Issue by SweetVishnya** [google/fuzzing#91]
Hi!

Is it possible to continue after the first found crash?

**Comment by inferno-chromium** [comment]
https://www.mono-project.com/docs/debug+profile/clang/addresssanitizer/#never-stop

**Comment by SweetVishnya** [comment]
Will the crash files be saved with never-stop enabled?

**Comment by inferno-chromium** [comment]
> Will the crash files be saved with never-stop enabled?

Yes they do.

**Comment by SweetVishnya** [comment]
Thank you. I'll try this option.
